name: Oswaldo Romo


repo_names:
  - 
# Provide any URLs for your Videos
10-ux-ui-criticism:
  - http://youtube.com/shorts/894IsMSqSys

# Provide any URLs for your Data Models assignment
11-models-from-data:
  - 